import CropIcon, { crops } from './CropIcon';
import JoinItem from './JoinItem';

export default function () {
  return (
    <>
      <header>This is the header</header>

      <div class="join">
        {crops.map(crop =>
          <JoinItem groupName="CropSelectorRadioGroup">
            <div class="tooltip" data-tip={crop.name}>
              <CropIcon crop={crop} />
            </div>
          </JoinItem>
        )}
      </div>

      <footer class="footer sm:footer-horizontal footer-center bg-base-300 text-base-content p-4">
        <aside>
          <p>Uses resources generated by Meta AI with Llama 4</p>
        </aside>
      </footer>
    </>
  );
}
